# Generated by Django 4.2.1 on 2023-05-28 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cart_delete_carts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={},
        ),
    ]
